name: NoxMMO
version: ${project.version}
description: Nox MMO system.
main: com.noxpvp.mmo.NoxMMO
author: Christopher Krier (AKA Coaster3000)
depend: [NoxCore]
commands:
  class:
    description: Class commands.
    usage: /<command> -h
  ability:
    description: Ability Commands
    usage: /<command> [Ability Name]