name: NoxCore
version: ${project.version}
main: ${main}
depend: [BKCommonLib]
softdepend: [Vault, Votifier, BarAPI, ProtocolLib, Towny, WorldGuard]
commands:
  reloader:
    description: Reload any plugin. 
  noxcore:
    description: Current does nothing.
    alias: [noxcore]