name: NoxCore
version: ${project.version}
main: ${main}
depend: [BKCommonLib, BarAPI]
softdepend: [Vault, Votifier, ProtocolLib, Towny, WorldGuard, HoloAPI]
commands:
  reloader:
    description: Reload any plugin. 
  nox:
    description: Current does nothing.
    alias: [noximperials]